development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  petfinder_key: <%= ENV["PETFINDER_KEY"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  petfinder_key: <%= ENV["PETFINDER_KEY"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  petfinder_key: <%= ENV["PETFINDER_KEY"] %>

